//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon_ID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon_ID()
        {
            this.ChiTietHD = new HashSet<ChiTietHD>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NhanVien_ID { get; set; }
        public Nullable<int> KhachHang_ID { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD> ChiTietHD { get; set; }
        public virtual KhachHang_ID KhachHang_ID1 { get; set; }
        public virtual NhanVien_ID NhanVien_ID1 { get; set; }
    }
}
