//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webnangcaoEntities : DbContext
    {
        public webnangcaoEntities()
            : base("name=webnangcaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardDoHoa> CardDoHoa { get; set; }
        public virtual DbSet<Chip_ID> Chip_ID { get; set; }
        public virtual DbSet<ChiTietHD> ChiTietHD { get; set; }
        public virtual DbSet<HoaDon_ID> HoaDon_ID { get; set; }
        public virtual DbSet<KhachHang_ID> KhachHang_ID { get; set; }
        public virtual DbSet<Loai_ID> Loai_ID { get; set; }
        public virtual DbSet<ManHinh_ID> ManHinh_ID { get; set; }
        public virtual DbSet<NhanVien_ID> NhanVien_ID { get; set; }
        public virtual DbSet<NhaSanXuat_ID> NhaSanXuat_ID { get; set; }
        public virtual DbSet<OCung_ID> OCung_ID { get; set; }
        public virtual DbSet<RAM_ID> RAM_ID { get; set; }
        public virtual DbSet<SanPham_ID> SanPham_ID { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TinhTrang_ID> TinhTrang_ID { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_detail> Order_detail { get; set; }
    }
}
