//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_ID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham_ID()
        {
            this.ChiTietHD = new HashSet<ChiTietHD>();
        }
    
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> NhaSanXuat_ID { get; set; }
        public Nullable<int> Loai_ID { get; set; }
        public Nullable<int> ManHinh_ID { get; set; }
        public Nullable<int> Ram_ID { get; set; }
        public Nullable<int> OCung_ID { get; set; }
        public Nullable<int> Chip_ID { get; set; }
        public Nullable<int> TinhTrang_ID { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> CardDoHoa_ID { get; set; }
        public string Cong { get; set; }
        public string image { get; set; }
    
        public virtual CardDoHoa CardDoHoa { get; set; }
        public virtual Chip_ID Chip_ID1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD> ChiTietHD { get; set; }
        public virtual Loai_ID Loai_ID1 { get; set; }
        public virtual ManHinh_ID ManHinh_ID1 { get; set; }
        public virtual NhaSanXuat_ID NhaSanXuat_ID1 { get; set; }
        public virtual OCung_ID OCung_ID1 { get; set; }
        public virtual RAM_ID RAM_ID1 { get; set; }
        public virtual TinhTrang_ID TinhTrang_ID1 { get; set; }
    }
}
